repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^migrations/
      - id: end-of-file-fixer
        exclude: ^migrations/
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: debug-statements

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: []
        exclude: ^migrations/
        args:
          - --max-line-length=120
          - --extend-ignore=E501,W503,E402

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy app/ scheduler/
        language: system
        pass_filenames: false
        always_run: true
