FROM mcr.microsoft.com/playwright/python:v1.52.0-noble

WORKDIR /e2e

RUN apt-get update -qq && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

COPY requirements-e2e.txt /requirements-e2e.txt
RUN pip install --quiet --no-cache-dir -r /requirements-e2e.txt \
    && playwright install --with-deps chromium firefox webkit
