"""Shared utility helpers for the MedCover application."""

from __future__ import annotations

from typing import TypeVar
from urllib.parse import urlsplit
from zoneinfo import ZoneInfo

T = TypeVar("T")
E = TypeVar("E")

# ── Timezone ──────────────────────────────────────────────────────────────────

_DEFAULT_TZ = "Europe/Prague"


def get_app_tz() -> ZoneInfo:
    """Return the application timezone from AppSettings.

    Falls back to Europe/Prague when settings are unavailable (e.g. during
    initial setup before the DB is seeded, or in CLI commands).
    """
    try:
        from app.models.settings import get_settings  # pylint: disable=import-outside-toplevel

        settings = get_settings()
        if settings and settings.timezone:
            return ZoneInfo(settings.timezone)
    except Exception:  # noqa: BLE001
        pass
    return ZoneInfo(_DEFAULT_TZ)


# ── Czech locale-aware sorting ────────────────────────────────────────────────

# PostgreSQL ICU collation name to use in all order_by() calls where
# user-visible names are sorted.  cs-x-icu provides proper Czech alphabet
# ordering (a á b c č d ď e é ě … ch … ř š … ž) within the DB engine.
CS_COLLATION = "cs-x-icu"

# Czech alphabet in correct order including digraph 'ch'.
_CS_ALPHABET: list[str] = [
    "a",
    "á",
    "b",
    "c",
    "č",
    "d",
    "ď",
    "e",
    "é",
    "ě",
    "f",
    "g",
    "h",
    "ch",
    "i",
    "í",
    "j",
    "k",
    "l",
    "m",
    "n",
    "ň",
    "o",
    "ó",
    "p",
    "q",
    "r",
    "ř",
    "s",
    "š",
    "t",
    "ť",
    "u",
    "ú",
    "ů",
    "v",
    "w",
    "x",
    "y",
    "ý",
    "z",
    "ž",
]
_CS_RANK: dict[str, int] = {ch: i for i, ch in enumerate(_CS_ALPHABET)}
_CS_FALLBACK = len(_CS_ALPHABET)


def czech_sort_key(text: str) -> list[int]:
    """Return a sort-key list for Czech locale-aware string comparison.

    Handles the 'ch' digraph (sorts between 'h' and 'i') and all standard
    Czech diacritic letters.  Use as the ``key=`` argument for Python-level
    sorts that cannot be pushed to the database.

    Example::

        users.sort(key=lambda u: czech_sort_key(u.name))
    """
    s = text.lower()
    result: list[int] = []
    i = 0
    while i < len(s):
        if s[i] == "c" and i + 1 < len(s) and s[i + 1] == "h":
            result.append(_CS_RANK["ch"])
            i += 2
        else:
            result.append(_CS_RANK.get(s[i], _CS_FALLBACK + ord(s[i])))
            i += 1
    return result


def safe_next(next_url: str | None, fallback: str | None = None) -> str:
    """Return *next_url* only if it is a same-origin relative path.

    Rejects absolute URLs, scheme-relative URLs (``//evil.example``),
    and empty/``None`` values.  Falls back to *fallback* if provided,
    otherwise to the main dashboard.

    Use this **everywhere** the app redirects to a user-supplied URL.
    """
    from flask import url_for  # pylint: disable=import-outside-toplevel

    _fallback = fallback or url_for("main.dashboard")
    if not next_url:
        return _fallback
    parsed = urlsplit(next_url)
    if parsed.scheme or parsed.netloc:
        return _fallback
    return next_url


def external_url_for(endpoint: str, **values: object) -> str:
    """Build an absolute URL for *endpoint*, honouring the configured ``app_base_url``.

    When ``AppSettings.app_base_url`` is set (e.g. ``https://medcoverdev.spidermila.site``),
    that base is prepended to the path generated by Flask's ``url_for``.  This ensures that
    links in e-mails (password reset, invitations, activation notices) point to the
    publicly accessible address even when the app runs behind a reverse proxy.

    Falls back to Flask's built-in ``_external=True`` behaviour when no base URL is
    configured so that local / test environments still produce valid links.
    """
    from flask import url_for  # pylint: disable=import-outside-toplevel

    try:
        from app.models.settings import get_settings  # pylint: disable=import-outside-toplevel

        base: str | None = get_settings().app_base_url
    except Exception:
        base = None

    path = url_for(endpoint, **values)  # type: ignore[arg-type]
    if base:
        return base.rstrip("/") + path
    return url_for(endpoint, _external=True, **values)  # type: ignore[arg-type]


def diff_changes(before: dict, after: dict) -> dict:
    """Return {field: [old_val, new_val]} for fields whose values changed.

    Compares using string representation so None and '' differences are caught.
    Only includes fields that actually changed — fields with identical values
    before and after are omitted.

    Example:
        before = {"name": "Old", "desc": None}
        after  = {"name": "New", "desc": None}
        → {"name": ["Old", "New"]}
    """
    all_keys = set(list(before.keys()) + list(after.keys()))
    return {k: [before.get(k), after.get(k)] for k in sorted(all_keys) if str(before.get(k)) != str(after.get(k))}


def audit(
    action: str,
    entity_type: str,
    entity_id: str | int,
    summary: str,
    changes: dict | None = None,
) -> None:
    """Append an ``AuditLogEntry`` for the current user to the active DB session.

    The caller is responsible for committing. Use within a transaction so that
    the audit row is rolled back together with the business change on failure.
    """
    from flask_login import current_user  # pylint: disable=import-outside-toplevel

    from app.extensions import db  # pylint: disable=import-outside-toplevel
    from app.models.audit import AuditLogEntry  # pylint: disable=import-outside-toplevel

    db.session.add(
        AuditLogEntry(
            actor_id=current_user.id,
            action_type=action,
            entity_type=entity_type,
            entity_id=str(entity_id),
            summary=summary,
            changes_json=changes,
        )
    )


def get_or_404(model: type[T], pk: object) -> T:
    """Fetch *model* by primary key; abort 404 if missing.

    Standard idiom for view functions to resolve a URL parameter to an entity.
    """
    from flask import abort  # pylint: disable=import-outside-toplevel

    from app.extensions import db  # pylint: disable=import-outside-toplevel

    obj = db.session.get(model, pk)
    if obj is None:
        abort(404)
    return obj  # type: ignore[return-value]


def require_permission(*codes: str) -> None:
    """Abort 403 unless the current user holds at least one of *codes*.

    Call inline at the top of view functions that already use ``@login_required``.
    """
    from flask import abort  # pylint: disable=import-outside-toplevel
    from flask_login import current_user  # pylint: disable=import-outside-toplevel

    if not current_user.has_any_permission(*codes):
        abort(403)


def check_version_conflict(obj: object, form_value: str | None) -> bool:
    """Return True if the form's submitted version doesn't match ``obj.version``.

    Used for optimistic-locking edit forms — caller flashes
    :data:`RECORD_MODIFIED_MSG` and re-renders the form when this returns True.
    """
    try:
        submitted = int(form_value or 0)
    except (TypeError, ValueError):
        submitted = 0
    current = getattr(obj, "version", None)
    return current is not None and submitted != current


def parse_enum(enum_class: type[E], value: object, default: E | None = None) -> E | None:
    """Coerce *value* to *enum_class*; return *default* on failure."""
    if value is None:
        return default
    try:
        return enum_class(value)  # type: ignore[call-arg]
    except (ValueError, KeyError):
        return default


# ── Date-range quick-fill buttons ─────────────────────────────────────────────


def quick_date_ranges() -> list[tuple[str, str, str]]:
    """Return (label, from_date_iso, to_date_iso) tuples for quick-fill buttons.

    Used by the date-range report and debriefing manage page.
    """
    from calendar import monthrange  # pylint: disable=import-outside-toplevel
    from datetime import date  # pylint: disable=import-outside-toplevel

    today = date.today()
    tm_from = today.replace(day=1)
    tm_to = today.replace(day=monthrange(today.year, today.month)[1])
    lm_year, lm_month = (today.year - 1, 12) if today.month == 1 else (today.year, today.month - 1)
    lm_from = date(lm_year, lm_month, 1)
    lm_to = date(lm_year, lm_month, monthrange(lm_year, lm_month)[1])
    ty_from = date(today.year, 1, 1)
    ty_to = date(today.year, 12, 31)
    return [
        ("Tento měsíc", tm_from.isoformat(), tm_to.isoformat()),
        ("Minulý měsíc", lm_from.isoformat(), lm_to.isoformat()),
        ("Od začátku roku", ty_from.isoformat(), today.isoformat()),
        ("Celý rok", ty_from.isoformat(), ty_to.isoformat()),
    ]
