"""add password_reset_nonce to user_account

Revision ID: 1613fcb025fb
Revises: 36dc707e1bbc
Create Date: 2026-05-09 10:20:03.791110

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1613fcb025fb"
down_revision = "36dc707e1bbc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_reset_nonce", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("password_reset_nonce")

    # ### end Alembic commands ###
