"""add_dev_email_block_to_app_settings

Revision ID: 1a19cb432044
Revises: 9159338cf432
Create Date: 2026-05-08 15:42:09.138554

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '1a19cb432044'
down_revision = '9159338cf432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_email_block', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('dev_email_allowlist', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('dev_email_allowlist')
        batch_op.drop_column('dev_email_block')

    # ### end Alembic commands ###
