"""debriefing redesign: new fields on assignment, event, debriefing_record

Revision ID: 20dbd30fbcfe
Revises: 86ba4668fbf9
Create Date: 2026-05-09 15:24:55.347000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20dbd30fbcfe"
down_revision = "86ba4668fbf9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("debriefing_email_sent", sa.Boolean(), nullable=False, server_default="false"))

    with op.batch_alter_table("debriefing_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade", sa.Integer(), nullable=False, server_default="3"))
        batch_op.add_column(sa.Column("feedback_event", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("feedback_customer", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("feedback_colleagues", sa.Text(), nullable=True))
        batch_op.drop_column("actual_hours")
        batch_op.drop_column("patients_treated")
        batch_op.drop_column("feedback")
        batch_op.drop_column("materials_used")

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("actual_start_datetime", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("actual_end_datetime", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("patients_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("patients_count")
        batch_op.drop_column("actual_end_datetime")
        batch_op.drop_column("actual_start_datetime")

    with op.batch_alter_table("debriefing_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("materials_used", sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("feedback", sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column("patients_treated", sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column("actual_hours", sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False)
        )
        batch_op.drop_column("feedback_colleagues")
        batch_op.drop_column("feedback_customer")
        batch_op.drop_column("feedback_event")
        batch_op.drop_column("grade")

    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_column("debriefing_email_sent")

    # ### end Alembic commands ###
