"""template_equipment_plan

Revision ID: 2b096852ef02
Revises: ebe3ddc11f1e
Create Date: 2026-05-08 00:09:39.540720

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2b096852ef02'
down_revision = 'ebe3ddc11f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_template_equipment_plan',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['event_template.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'equipment_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_template_equipment_plan')
    # ### end Alembic commands ###
