"""mssql baseline schema

Revision ID: 2dbbf9629c3f
Revises: 
Create Date: 2026-06-19 15:27:36.374850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbbf9629c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('app_base_url', sa.String(length=512), nullable=True),
    sa.Column('smtp_server', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_enc', sa.Text(), nullable=True),
    sa.Column('smtp_default_sender', sa.String(length=255), nullable=True),
    sa.Column('dev_email_block', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dev_email_allowlist', sa.Text(), nullable=True),
    sa.Column('backup_dir', sa.String(length=512), server_default='backups', nullable=False),
    sa.Column('backup_keep_count', sa.Integer(), server_default='7', nullable=False),
    sa.Column('backup_schedule_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('backup_schedule_hour', sa.Integer(), server_default='2', nullable=False),
    sa.Column('session_timeout_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('notify_assignment', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_event_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_assignments_opened', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_event_cancelled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_event_changed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_unfilled_reminder', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_debriefing', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('setup_complete', sa.Boolean(), nullable=False),
    sa.Column('feedback_enabled', sa.Boolean(), nullable=False),
    sa.Column('scheduler_last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digest_metric_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_metric_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_metric_snapshot_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_digest_metric_snapshot_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('digest_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('frequency_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('preferred_hour', sa.Integer(), server_default='7', nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_subject', sa.String(length=255), server_default='MedCover — Přehledový e-mail', nullable=False),
    sa.Column('header_html', sa.Text(), nullable=True),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PERSONAL', 'SHARED', name='equipment_category_enum'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('event_type', sa.Enum('MEDICAL_COVER', 'TRAINING', 'PRESENTATION', name='event_type_enum'), nullable=False),
    sa.Column('reminder_schedule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outbox_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=64), nullable=True),
    sa.Column('instance_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_email_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_email_instance_name'), ['instance_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_email_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_email_status'), ['status'], unique=False)

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('can_be_rp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.create_index('ix_qualification_name_active_unique', ['name'], unique=True, mssql_where=sa.text('is_deleted = 0'))

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preferred_calendar_view', sa.Enum('MONTH', 'WEEK', 'DAY', 'LIST', name='calendar_view_enum'), nullable=False),
    sa.Column('dashboard_horizon_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('dark_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('password_reset_nonce', sa.String(length=64), nullable=True),
    sa.Column('ical_token', sa.String(length=64), nullable=True),
    sa.Column('ical_all_token', sa.String(length=64), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('login_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_account_ical_all_token'), ['ical_all_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_account_ical_token'), ['ical_token'], unique=True)

    op.create_table('audit_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_entry_timestamp'), ['timestamp'], unique=False)

    op.create_table('digest_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_schedule_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('config_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['digest_schedule_id'], ['digest_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_block_digest_schedule_id'), ['digest_schedule_id'], unique=False)

    op.create_table('equipment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('home_location', sa.String(length=255), nullable=True),
    sa.Column('issued_to_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='equipment_item_status_enum'), server_default='AVAILABLE', nullable=False),
    sa.Column('unavailability_reason', sa.Text(), nullable=True),
    sa.Column('unavailability_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_to_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_spot_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['event_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_template_equipment_plan',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['event_template.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'equipment_type_id')
    )
    op.create_table('master_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinator_id', sa.Uuid(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('qualification_parents',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.PrimaryKeyConstraint('qualification_id', 'parent_id')
    )
    op.create_table('registration_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outbox_email_id', sa.Integer(), nullable=True),
    sa.Column('link_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_subject', sa.String(length=255), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['outbox_email_id'], ['outbox_email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_invite_token'), ['token'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=2048), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('screen_info', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('user_qualifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'qualification_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('master_event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MEDICAL_COVER', 'TRAINING', 'PRESENTATION', name='event_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ASSIGNMENTS_OPEN', 'ASSIGNMENTS_CLOSED', 'COMPLETED', 'CANCELLED', name='event_status_enum'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assignments_open_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_person_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_schedule', sa.String(length=255), nullable=True),
    sa.Column('reminder_sent_json', sa.JSON(), nullable=True),
    sa.Column('actual_start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_participants_count', sa.Integer(), nullable=True),
    sa.Column('post_event_count', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['master_event_id'], ['master_event.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spot_template_qualifications',
    sa.Column('spot_template_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['spot_template_id'], ['event_spot_template.id'], ),
    sa.PrimaryKeyConstraint('spot_template_id', 'qualification_id')
    )
    op.create_table('event_equipment_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_item_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_item.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'equipment_item_id', name='uq_event_equipment_item')
    )
    op.create_table('event_equipment_plan',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'equipment_type_id')
    )
    op.create_table('event_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('debriefing_email_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['event_spot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spot_id')
    )
    op.create_table('spot_qualifications',
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['event_spot.id'], ),
    sa.PrimaryKeyConstraint('spot_id', 'qualification_id')
    )
    op.create_table('debriefing_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('feedback_event', sa.Text(), nullable=True),
    sa.Column('feedback_customer', sa.Text(), nullable=True),
    sa.Column('feedback_colleagues', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debriefing_record')
    op.drop_table('spot_qualifications')
    op.drop_table('assignment')
    op.drop_table('event_spot')
    op.drop_table('event_equipment_plan')
    op.drop_table('event_equipment_assignment')
    op.drop_table('spot_template_qualifications')
    op.drop_table('event')
    op.drop_table('user_roles')
    op.drop_table('user_qualifications')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))

    op.drop_table('user_feedback')
    op.drop_table('role_permissions')
    with op.batch_alter_table('registration_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_invite_token'))

    op.drop_table('registration_invite')
    op.drop_table('qualification_parents')
    op.drop_table('master_event')
    op.drop_table('event_template_equipment_plan')
    op.drop_table('event_spot_template')
    op.drop_table('equipment_item')
    with op.batch_alter_table('digest_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_block_digest_schedule_id'))

    op.drop_table('digest_block')
    with op.batch_alter_table('audit_log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entry_timestamp'))

    op.drop_table('audit_log_entry')
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_ical_token'))
        batch_op.drop_index(batch_op.f('ix_user_account_ical_all_token'))
        batch_op.drop_index(batch_op.f('ix_user_account_email'))

    op.drop_table('user_account')
    op.drop_table('role')
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_index('ix_qualification_name_active_unique', mssql_where=sa.text('is_deleted = 0'))

    op.drop_table('qualification')
    op.drop_table('permission')
    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_email_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_email_notification_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_email_instance_name'))
        batch_op.drop_index(batch_op.f('ix_outbox_email_created_at'))

    op.drop_table('outbox_email')
    op.drop_table('event_template')
    op.drop_table('equipment_type')
    op.drop_table('digest_schedule')
    with op.batch_alter_table('digest_metric_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_metric_snapshot_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_digest_metric_snapshot_metric_name'))

    op.drop_table('digest_metric_snapshot')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
