"""add can_be_rp to qualification

Revision ID: 36dc707e1bbc
Revises: f0c168424643
Create Date: 2026-05-08 21:00:20.557256

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '36dc707e1bbc'
down_revision = 'f0c168424643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_be_rp', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_column('can_be_rp')

    # ### end Alembic commands ###
