"""add invite cancelled_at

Revision ID: 4ec25aa941b8
Revises: ad27f656e221
Create Date: 2026-05-07 21:06:30.909279

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ec25aa941b8"
down_revision = "ad27f656e221"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.drop_column("cancelled_at")

    # ### end Alembic commands ###
