"""add dashboard_horizon_days to user_account

Revision ID: 5a65ab309cfc
Revises: f8edde653722
Create Date: 2026-05-07 07:20:38.582311

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5a65ab309cfc"
down_revision = "f8edde653722"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dashboard_horizon_days", sa.Integer(), server_default="30", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("dashboard_horizon_days")

    # ### end Alembic commands ###
