"""add dark_mode to user_account

Revision ID: 5bf568d4f009
Revises: a730e4af594e
Create Date: 2026-05-07 12:53:30.722629

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5bf568d4f009"
down_revision = "a730e4af594e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dark_mode", sa.Boolean(), server_default="false", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_column("dark_mode")

    # ### end Alembic commands ###
