"""add scheduler_last_seen to app_settings

Revision ID: 67dfa2385f16
Revises: ac1ab7d64f6c
Create Date: 2026-05-07 11:03:07.643412

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "67dfa2385f16"
down_revision = "ac1ab7d64f6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scheduler_last_seen", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("scheduler_last_seen")

    # ### end Alembic commands ###
