"""qualification_soft_delete

Revision ID: 6afec7c90ac1
Revises: 4ec25aa941b8
Create Date: 2026-05-07 22:40:26.217761

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6afec7c90ac1'
down_revision = '4ec25aa941b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(batch_op.f('credential_name_key'), type_='unique')
        batch_op.create_index('ix_qualification_name_active_unique', ['name'], unique=True, postgresql_where=sa.text('is_deleted = false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_index('ix_qualification_name_active_unique', postgresql_where=sa.text('is_deleted = false'))
        batch_op.create_unique_constraint(batch_op.f('credential_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
