"""add backup config to app_settings

Revision ID: 86ba4668fbf9
Revises: 1613fcb025fb
Create Date: 2026-05-09 10:49:39.996039

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86ba4668fbf9"
down_revision = "1613fcb025fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backup_dir", sa.String(length=512), server_default="backups", nullable=False))
        batch_op.add_column(sa.Column("backup_keep_count", sa.Integer(), server_default="7", nullable=False))
        batch_op.add_column(sa.Column("backup_schedule_enabled", sa.Boolean(), server_default="false", nullable=False))
        batch_op.add_column(sa.Column("backup_schedule_hour", sa.Integer(), server_default="2", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("backup_schedule_hour")
        batch_op.drop_column("backup_schedule_enabled")
        batch_op.drop_column("backup_keep_count")
        batch_op.drop_column("backup_dir")

    # ### end Alembic commands ###
