"""add invite email tracking columns

Revision ID: 8af3e067c0c6
Revises: a1b2c3d4e5f6
Create Date: 2026-05-07 20:54:26.459428

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8af3e067c0c6"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.add_column(sa.Column("outbox_email_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("link_clicked_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, "outbox_email", ["outbox_email_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("link_clicked_at")
        batch_op.drop_column("outbox_email_id")

    # ### end Alembic commands ###
