"""add_reminder_sent_json_to_event

Revision ID: 9159338cf432
Revises: d946eda56491
Create Date: 2026-05-08 15:37:12.072855

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9159338cf432"
down_revision = "d946eda56491"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reminder_sent_json", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_column("reminder_sent_json")

    # ### end Alembic commands ###
