"""add session_timeout_hours to app_settings

Revision ID: 9b422409dc10
Revises: 661e4a600825
Create Date: 2026-05-13 07:13:21.009345

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b422409dc10"
down_revision = "661e4a600825"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_timeout_hours", sa.Integer(), server_default="24", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("session_timeout_hours")
    # ### end Alembic commands ###
