"""add_app_base_url_to_app_settings

Revision ID: 9fd3c08b3d50
Revises: bbd2db07fc29
Create Date: 2026-05-08 15:09:43.396867

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fd3c08b3d50"
down_revision = "bbd2db07fc29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("app_base_url", sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("app_base_url")

    # ### end Alembic commands ###
