"""add version to event_template

Revision ID: a730e4af594e
Revises: b39e55598ad1
Create Date: 2026-05-07 12:10:53.405158

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a730e4af594e'
down_revision = 'b39e55598ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_template', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
