"""add outbox_email table for queued email delivery

Revision ID: ac1ab7d64f6c
Revises: 5a65ab309cfc
Create Date: 2026-05-07 07:51:46.126473

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ac1ab7d64f6c'
down_revision = '5a65ab309cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_email_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_email_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_email_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_email_created_at'))

    op.drop_table('outbox_email')
    # ### end Alembic commands ###
