"""add invite custom subject and message

Revision ID: ad27f656e221
Revises: 8af3e067c0c6
Create Date: 2026-05-07 21:01:55.690434

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad27f656e221"
down_revision = "8af3e067c0c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.add_column(sa.Column("custom_subject", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("custom_message", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("registration_invite", schema=None) as batch_op:
        batch_op.drop_column("custom_message")
        batch_op.drop_column("custom_subject")

    # ### end Alembic commands ###
