"""add equipment models

Revision ID: b39e55598ad1
Revises: 67dfa2385f16
Create Date: 2026-05-07 11:59:23.951638

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b39e55598ad1'
down_revision = '67dfa2385f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PERSONAL', 'SHARED', name='equipment_category_enum'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('home_location', sa.String(length=255), nullable=True),
    sa.Column('issued_to_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_to_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_equipment_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_item_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_item.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'equipment_item_id', name='uq_event_equipment_item')
    )
    op.create_table('event_equipment_plan',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'equipment_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_equipment_plan')
    op.drop_table('event_equipment_assignment')
    op.drop_table('equipment_item')
    op.drop_table('equipment_type')
    # ### end Alembic commands ###
