"""add equipment item status and unavailability fields

Revision ID: b801953d30cb
Revises: 150aa748aa4f
Create Date: 2026-05-14 16:29:27.284836

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b801953d30cb"
down_revision = "150aa748aa4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assignment_user_id"))

    op.execute("CREATE TYPE equipment_item_status_enum AS ENUM ('AVAILABLE', 'UNAVAILABLE')")

    with op.batch_alter_table("equipment_item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("AVAILABLE", "UNAVAILABLE", name="equipment_item_status_enum", create_type=False),
                server_default="AVAILABLE",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("unavailability_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("unavailability_since", sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_archived"))
        batch_op.drop_index(batch_op.f("ix_event_archived_status_start"))
        batch_op.drop_index(batch_op.f("ix_event_master_event_id"))
        batch_op.drop_index(batch_op.f("ix_event_start_datetime"))
        batch_op.drop_index(batch_op.f("ix_event_status"))

    with op.batch_alter_table("event_spot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_spot_event_id"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_spot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_spot_event_id"), ["event_id"], unique=False)

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_start_datetime"), ["start_datetime"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_master_event_id"), ["master_event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_event_archived_status_start"), ["archived", "status", "start_datetime"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_event_archived"), ["archived"], unique=False)

    with op.batch_alter_table("equipment_item", schema=None) as batch_op:
        batch_op.drop_column("unavailability_since")
        batch_op.drop_column("unavailability_reason")
        batch_op.drop_column("status")

    op.execute("DROP TYPE IF EXISTS equipment_item_status_enum")

    with op.batch_alter_table("assignment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assignment_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###
