"""add user_feedback table

Revision ID: bbd2db07fc29
Revises: 2b096852ef02
Create Date: 2026-05-08 14:24:55.674563

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbd2db07fc29"
down_revision = "2b096852ef02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("screen_info", sa.String(length=255), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_feedback_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_feedback_user_id"))

    op.drop_table("user_feedback")
    # ### end Alembic commands ###
