"""add_feedback_version_and_enabled_toggle

Revision ID: d946eda56491
Revises: 9fd3c08b3d50
Create Date: 2026-05-08 15:23:06.495967

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd946eda56491'
down_revision = '9fd3c08b3d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_version', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_column('app_version')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('feedback_enabled')

    # ### end Alembic commands ###
