"""optional_spots

Revision ID: ebe3ddc11f1e
Revises: 6afec7c90ac1
Create Date: 2026-05-07 23:52:52.839155

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ebe3ddc11f1e'
down_revision = '6afec7c90ac1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('event_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_optional', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('event_spot_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_optional', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_spot_template', schema=None) as batch_op:
        batch_op.drop_column('is_optional')

    with op.batch_alter_table('event_spot', schema=None) as batch_op:
        batch_op.drop_column('is_optional')

    # ### end Alembic commands ###
