"""add_digest_tables_and_outbox_html_body

Revision ID: f0c168424643
Revises: 1a19cb432044
Create Date: 2026-05-08 17:34:51.229603

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f0c168424643'
down_revision = '1a19cb432044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_metric_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_metric_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_metric_snapshot_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_digest_metric_snapshot_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('digest_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('frequency_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('preferred_hour_utc', sa.Integer(), server_default='7', nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_subject', sa.String(length=255), server_default='MedCover — Přehledový e-mail', nullable=False),
    sa.Column('header_html', sa.Text(), nullable=True),
    sa.Column('footer_html', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digest_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_schedule_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('config_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['digest_schedule_id'], ['digest_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digest_block', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digest_block_digest_schedule_id'), ['digest_schedule_id'], unique=False)

    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_email', schema=None) as batch_op:
        batch_op.drop_column('html_body')

    with op.batch_alter_table('digest_block', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_block_digest_schedule_id'))

    op.drop_table('digest_block')
    op.drop_table('digest_schedule')
    with op.batch_alter_table('digest_metric_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digest_metric_snapshot_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_digest_metric_snapshot_metric_name'))

    op.drop_table('digest_metric_snapshot')
    # ### end Alembic commands ###
