"""add version columns for optimistic locking

Revision ID: f8edde653722
Revises: dfc13fca938f
Create Date: 2026-05-07 06:36:33.891891

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f8edde653722'
down_revision = 'dfc13fca938f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('event_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('master_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('master_event', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('event_spot', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
